---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flux-terragrunt-controller.fullname" . }}-config
  labels:
    {{- include "flux-terragrunt-controller.labels" . | nindent 4 }}
data:
  # Placeholder config entries
  TERRAGRUNT_ENABLED: "true"
