---
replicaCount: 1

image:
  repository: flux-terragrunt-controller
  tag: "0.0.1"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

metrics:
  enabled: false
  port: 8080
